# -*- coding: utf-8 -*-
"""VGG16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYkgmQkNdfAw8u6bi22w66ZDmPunj4uQ
"""

# 한글 폰트 설치 (나눔체) - 시각화 시 用

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# Github에서 데이터 불러온 후 zip파일 압축 해제

!wget https://github.com/jwdebbie/knife-classification/raw/main/knives_dataset.zip
!unzip -q knives_dataset.zip

# 메타데이터 생성

import os
import pandas as pd

origin = '/content/knives_dataset'
data = []

for folder in os.listdir(origin):
    folder_path = os.path.join(origin, folder)
    if not os.path.isdir(folder_path):
        continue

    parts = folder.split('_')
    if len(parts) != 5:
        continue

    번호, 조도, 배경, 칼종류, 오클루전 = parts

    for file in os.listdir(folder_path):
        if file.lower().endswith(('.jpg', '.png')):
            data.append({
                '파일명': file,
                '폴더명': folder,
                '조도': 조도,
                '배경': 배경,
                '칼종류': 칼종류,
                '오클루전': 오클루전,
                '전체경로': os.path.join(folder_path, file)
            })

df_meta = pd.DataFrame(data)

# 메타데이터 생성 여부 확인

df_meta['칼종류'].value_counts()

# 칼 종류별(식칼, 과도, 커터칼) 정리된 폴더 구조 생성

import os
import shutil

origin = '/content/knives_dataset'
base_dir = '/content/knife_class_dataset'
classes = ['식칼', '과도', '커터칼']
os.makedirs(base_dir, exist_ok=True)

for folder in os.listdir(origin):
    for c in classes:
        if c in folder:
            target_dir = os.path.join(base_dir, c)
            os.makedirs(target_dir, exist_ok=True)
            for file in os.listdir(os.path.join(origin, folder)):
                src = os.path.join(origin, folder, file)
                dst = os.path.join(target_dir, file)
                shutil.copy(src, dst)

# ImageDataGenerator로 칼 종류 기준 분류 학습용 데이터 구성

from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_gen = datagen.flow_from_directory(
    base_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_gen = datagen.flow_from_directory(
    base_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

from tensorflow.keras.applications import VGG16
from tensorflow.keras import models, layers, optimizers

# 1. base model: VGG16 (ImageNet 가중치, fully connected layer 제거)
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False  # 처음에는 feature extractor로만 사용

# 2. 분류용 새 모델 구성
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dense(3, activation='softmax')  # 클래스 수 = 3 (식칼, 과도, 커터칼)
])

# 3. 컴파일
model.compile(
    optimizer=optimizers.Adam(),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# 4. 학습
history_vgg = model.fit(
    train_gen,
    epochs=10,
    validation_data=val_gen
)

# 검증셋 예측값 저장

import numpy as np

val_gen.reset()
pred_probs = model.predict(val_gen)
pred_classes = np.argmax(pred_probs, axis=1)
true_classes = val_gen.classes
class_labels = list(val_gen.class_indices.keys())

# 파일 경로 목록도 저장
filenames = val_gen.filenames

# 예측 결과 DataFrame 만들기

import pandas as pd

df_pred = pd.DataFrame({
    '파일경로': filenames,
    '실제클래스': [class_labels[i] for i in true_classes],
    '예측클래스': [class_labels[i] for i in pred_classes]
})

# df_meta와 merge (조건 붙이기)

# 파일명 컬럼 생성
df_pred['파일명'] = df_pred['파일경로'].apply(lambda x: x.split('/')[-1])

# df_meta에서 '파일명' 기준으로 merge
df_merged = pd.merge(df_pred, df_meta, on='파일명', how='left')

# 조건별 정확도 분석

# 조도별 정확도
조도별정확도 = df_merged.groupby('조도').apply(lambda x: (x['실제클래스'] == x['예측클래스']).mean())
print(" 조도별 정확도:\n", 조도별정확도)

# 오클루전 여부별 정확도
오클루전정확도 = df_merged.groupby('오클루전').apply(lambda x: (x['실제클래스'] == x['예측클래스']).mean())
print("\n 오클루전 여부별 정확도:\n", 오클루전정확도)

# 배경별 정확도
배경별정확도 = df_merged.groupby('배경').apply(lambda x: (x['실제클래스'] == x['예측클래스']).mean())
print("\n 배경별 정확도:\n", 배경별정확도)

# 칼 종류별 정확도 (촬영된 칼 종류 기준)
칼종류정확도 = df_merged.groupby('칼종류').apply(lambda x: (x['실제클래스'] == x['예측클래스']).mean())
print("\n 칼 종류별 정확도 (촬영 기준):\n", 칼종류정확도)

# 폴더명 기준 정확도 (영상 단위 분석)
폴더별정확도 = df_merged.groupby('폴더명').apply(lambda x: (x['실제클래스'] == x['예측클래스']).mean())
print("\n 폴더별 정확도 (전체 조건 조합):\n", 폴더별정확도)

import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic')

plt.plot(history_vgg.history['accuracy'], label='train acc')
plt.plot(history_vgg.history['val_accuracy'], label='val acc')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('VGG16 Accuracy')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

plt.rc('font', family='NanumBarunGothic')

cm = confusion_matrix(true_classes, pred_classes)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_labels)
disp.plot(cmap='Blues')
plt.title("VGG16 Confusion Matrix")
plt.show()

plt.rc('font', family='NanumBarunGothic')

def plot_accuracy_bar(data, title):
    plt.figure(figsize=(10, 5))
    plt.bar(data.index, data.values, color='lightsteelblue')
    plt.ylim(0, 1)
    plt.title(title)
    plt.ylabel("Accuracy")
    plt.xlabel("Category")
    plt.xticks(rotation=65, ha='right', fontsize=8)
    plt.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.show()


# 각 조건별 시각화
plot_accuracy_bar(조도별정확도, "Accuracy by Lighting (VGG16)")
plot_accuracy_bar(오클루전정확도, "Accuracy by Occlusion (VGG16)")
plot_accuracy_bar(배경별정확도, "Accuracy by Background (VGG16)")
plot_accuracy_bar(칼종류정확도, "Accuracy by Knife Type (VGG16)")
plot_accuracy_bar(폴더별정확도, "Accuracy by Folder (VGG16)")

vgg16_df = df_merged.copy()
vgg16_df.to_csv("vgg16_results.csv", index=False, encoding='cp949')